apiVersion: v1
kind: ConfigMap
metadata:
  name: aegisx-web-config
  labels:
    app: aegisx-web
    app.kubernetes.io/name: aegisx-web
    app.kubernetes.io/part-of: aegisx-platform
    component: frontend
data:
  APP_NAME: 'AegisX'
  ENABLE_DEBUG: 'false'
  API_URL: '' # Will be overridden in overlays
