apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

namePrefix: staging-

bases:
  - ../../../base/web

images:
  - name: ghcr.io/aegisx-platform/aegisx-starter-web
    newTag: staging

commonLabels:
  environment: staging

configMapGenerator:
  - name: aegisx-web-config
    behavior: merge
    literals:
      - API_URL= # Empty string - no prefix (same as API)
      - APP_NAME=AegisX Staging
      - ENABLE_DEBUG=true
